### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by gto76** [gto76/python-cheatsheet#12]
Cheatsheet
-----------
- [x] MemoryView
- [x] Pathlib
- [ ] Asyncio
- [x] Datetime
- [x] Logging
- [x] Dataclass

Page
-----
- [x] Static page (Automatic generation of `index.html` from `README.md` at commit)
- [x] Better mobile experience (Help needed)
- [x] Back to top button (Help needed)

**Comment by 0xbart** [comment]
Thanks for your awesome cheatsheet. But a question / addition: maybe some short sentences about PEP8?

**Comment by nevzat** [comment]
Please add DataClasses

**Comment by gto76** [comment]
I don't know how and where to incorporate PEP8. Also it would be kind of awkward to preach about it, since most examples don't follow it.

Didn't know about DataClasses. Will most probably squeeze them in somewhere. If there are any more useful 3.7 features, feel free to suggest.

**Comment by Kub-AT** [comment]
About DataClasses and "backports" for earlier versions
https://realpython.com/python-refactoring/#5-using-attrs-and-dataclasses-to-reduce-code

**Comment by RedactedCode** [comment]
lstrip(), rstrip()
f-strings

**Comment by jrmontag** [comment]
Great reference! It'd be great to see a section on the `typing` module https://docs.python.org/3/library/typing.html
